import React from 'react';
import Patient from './Patient.js';

function PatientList(props) {

  // Return the list with the medical treatments, generated by the MedicalTreatment component. 
  return props.patients.map((patient) => 
        <Patient item = {patient} setPatientState={props.setPatientState} />
    );
}

export default PatientList;