import React from 'react';
import Prescription from './Prescription';

function PrescriptionList(props) {

  // Return the list with the prescriptions, generated by the Prescription component. 
  return props.prescriptions.map((prescription) => 
        <Prescription item = {prescription} setPrescriptionState={props.setPrescriptionState} />
    );
}

export default PrescriptionList;