import React from 'react';
import Treatment from './Treatment.js';

function TreatmentList(props) {

  // Return the list with the medical treatments, generated by the MedicalTreatment component. 
  return props.treatments.map((treatment) => 
        <Treatment item = {treatment} setTreatmentState={props.setTreatmentState} />
    );
}

export default TreatmentList;